#!python

#!/usr/bin/env python3
import os
import sys
from glob import glob
from snakemake.utils import read_job_properties
import pdb


configfile:"config.json"

def format_species_name(sname):
	gmap = {"B":"Sebastolobus",
		"S":"Sebastes",
		"H":"Helicolenus"}
	genus, species = sname.split("-")[:3]
	genus2 = genus
	genus = gmap[genus]
	return "{genus}_{species}".format(genus=genus, species = species)

def full_name(fname):
	genus, species, sample = fname.split("-")[:1]
	return "{genus}-{species}_{sample}".format(genus=genus, species = species, sample=sample)

def get_inputs(wildcards):
	inputs = []

	for i, g1 in enumerate(config["genomes"]):
		for j, g2 in enumerate(config["genomes"]):	#			if j>=i:	continue
			species1, sample1 = g1.split("_")[1:3]
			species1 = format_species_name(species1)
			fullname1 = g1.split("_")[1:3]
			fullname1 = '_'.join(fullname1)
			species2, sample2 = g2.split("_")[1:3]
			species2 = format_species_name(species2)
			fullname2 = g2.split("_")[1:3]
			fullname2 = '_'.join(fullname2)
			if species1==species2:
				continue
			print(species1, sample1, fullname1, species2, sample2, fullname2)
			inputs.append("output/pairwise/{s1}-{s2}.aln".format(s1=species1,s2=species2))
	return inputs


rule all:
	input:
		get_inputs

rule pairmap_genomes:
	input:
		reference="output/{species1}/{fullname1}/assembly/minia_{fullname1}_k61.contigs.fa"
		query="output/{species2}/{fullname2}/assembly/minia_{fullname2}_k61.contigs.fa",
	output:
		paf="output/{species1}/{species2}_{sample1}/genome_align/align.{species1}.{species2}.paf",
		maf="output/{species1}/{species2}_{sample1}/genome_align/{species1}.{species2}.maf",
#		singmaf="output/{species1}/{species2}_{sample1}/genome_align/{species1}.{species2}.sing.maf"
###	params:
###		slurm_opts=lambda wildcards: " -n32 "
###			"--time 0-8:00:00 "
###			"-J {wildcards.species1}-{wildcards.species2} "
###			"-p defq "
###			"".format(species1=wildcards.species1, species2=wildcards.species2)
	shell:"""
		module load minimap2;
		minimap2 -t 32 -ax asm20 --cs=long -Lc \
			{input.reference} {input.query} \
			>output/{wildcards.species1}/{wildcards.species2}_{wildcards.sample1}/genome_align/tmp;
		sort -T output/{wildcards.species1}/{wildcards.species2}_{wildcards.sample1}/genome_align/ \
			--parallel=32 -k6,6 -k8,8n -k9,9nr \
			output/{wildcards.species1}/{wildcards.species2}_{wildcards.sample1}/genome_align/tmp >{output.paf};
		rm output/{wildcards.species1}/{wildcards.species2}_{wildcards.sample1}/genome_align/tmp;
		printf "##maf version=1\n" >{output.maf};
		paftools.js view -f maf {output.paf} \
			| tail -n +2 | \
			awk -v ref_species="${wildcards.species1}" -v query_species="${wildcards.species2}" \
			'{if(NR%4==3) {gsub("^s ","s "ref_species".",$0)} else if(NR%4==0) gsub("^s ","s "query_species".",$0); else if(NR%4==2) gsub("^a ","a score=",$0); print}' >>{output.maf};
#		single_cov2 {output.maf} >{output.singmaf};
	"""

