#!python

#!/usr/bin/env python3
import os
import sys
from glob import glob
from snakemake.utils import read_job_properties
import pdb

configfile: "busco_config.json"

def get_inputs(wildcards):
	inputs = []	
	for lineage, path in config["busco_libs"].items():
		for species in config["SAMPLES"]:
			inputs.append("output/busco/{species}/"
						  "run_busco_{species}_{lineage}/"
						  "short_summary_busco_{species}_{lineage}.txt"
						  "".format(species=species,
									lineage=lineage))
	return inputs

rule all: 
	input: 
  		get_inputs

rule busco_contigs:
	input:
		asmb="{species}_purged.t1.fasta",
	output:
		fn_out="output/busco/{species}/run_busco_{species}_{lineage}/short_summary_busco_{species}_{lineage}.txt",
	params:
		slurm_opts=lambda wildcards: "-N 1 " \
									"--time 0-24:00:00 " \
									"-A co_genomicdata " \
									"-p savio3_bigmem " \
									"-o log/busco_{species}_{lineage}.log " \
									"-J {species}_{lineage}_busco " \
									.format(species=wildcards.species, 
											lineage=wildcards.lineage)
	threads:
		24
	run:
		busco_path=config["busco_libs"][wildcards.lineage]	
		shell("""
			module load busco/3.1 \
					augustus/2.5.5 \
					hmmer \
					blast/2.2.26 gcc;
			AUGUSTUS_CONFIG_PATH="/global/home/users/rohitkolora/local_modules_sw/augustus/2.5.5/config/";
			python ~/local_modules_sw/busco/3.1/scripts/run_BUSCO.py \
				-i {asmb} \
				-o busco_{species}_{lineage} \
				-t output/busco/{species}/tmp_{lineage} \
				-c 32 \
				-m geno -sp zebrafish \
				-l {busco_path};
			mv run_busco_{species}_{lineage} output/busco/{species}/
			""".format(asmb = input.asmb,
					   species=wildcards.species,
					   lineage=wildcards.lineage,
					   busco_path=busco_path))
			
