#!python

#!/usr/bin/env python3
import os
import sys
from glob import glob
from snakemake.utils import read_job_properties
import pdb

configfile: "config.json"

def get_inputs(wildcards):
	inputs = []	
	for lineage, path in config["busco_libs"].items():
		for s in config["SAMPLES"]:
			species, smp = s.split("/")
			inputs.append("output/{species}/{smp}/"
						  "assembly/busco/"
						  "run_busco_{smp}_{lineage}/"
						  "short_summary_busco_{smp}_{lineage}.txt"
						  "".format(species=species,
									smp=smp,
									lineage=lineage))
	return inputs

rule all: 
	input: 
  		get_inputs

rule busco_4m_minia:
	input:
		asmb="output/{species}/{smp}/assembly/minia_{smp}_k61.contigs.fa",
		direc="output/{species}/{smp}/assembly/"
	output:
		fn_out="output/{species}/{smp}/assembly/busco/run_busco_{smp}_{lineage}/short_summary_busco_{smp}_{lineage}.txt",
	params:
		slurm_opts=lambda wildcards: "-n24 " \
									"--time 0-24:00:00 " \
									"-A co_genomicdata " \
									"-p savio2_bigmem " \
#									"-e log/busco_{smp}_{lineage}.log " \
									"-J {smp}_{lineage}_busco " \
									.format(smp=wildcards.smp, 
											lineage=wildcards.lineage)
	threads:
		24
	run:
		busco_path=config["busco_libs"][wildcards.lineage]	
		shell("""
			module load busco/3.1 \
					augustus/2.5.5 \
					hmmer \
					blast/2.2.26 gcc;
			AUGUSTUS_CONFIG_PATH="/global/home/users/rohitkolora/local_modules_sw/augustus/2.5.5/config/";
			python ~/local_modules_sw/busco/3.1/scripts/run_BUSCO.py \
				-i {asmb} \
				-o busco_{smp}_{lineage} \
				-t {input_dir}/busco/tmp_{lineage} \
				-c {threads} \
				-m geno -sp zebrafish \
				-l {busco_path};
			mv run_busco_{smp}_{lineage} output/{species}/{smp}/assembly/busco/
			""".format(asmb = input.asmb,
					   smp=wildcards.smp,
					   threads=threads,
					   input_dir = input.direc,
					   species=wildcards.species,
					   lineage=wildcards.lineage,
					   busco_path=busco_path))
			
