#!python

#!/usr/bin/env python3
import os
import sys
from glob import glob
from snakemake.utils import read_job_properties
import pdb

configfile: "config.json"

#workdir: "/global/scratch2/rohitkolora/Rockfish/Genomes/sequencing/illumina"

def get_inputs(wildcards):
	inputs = []	
	pattern = "output/{species}/{smp}/assembly/minia_k61.contigs.fa"
	for s in config["SAMPLES"]:
		species, sample = s.split("/")
		inputs.append(pattern.format(species=species,
									 smp=sample))
	return inputs

rule all: 
	input: 
  		get_inputs
    #expand("output/{smp}/assembly/minia_k61.contigs.fa", smp=config["SAMPLES"])

rule merge_corrected:
	input: 
		fwd="output/{species}/{smp}/corrected/corr.0", 
		rev="output/{species}/{smp}/corrected/corr.1",
	output: 
		fwd="output/{species}/{smp}/merged/overlapped.notCombined_1.fastq",
		rev="output/{species}/{smp}/merged/overlapped.notCombined_2.fastq",
		ext="output/{species}/{smp}/merged/overlapped.extendedFrags.fastq",
	threads:
		8
	shell: """
		module load flash
		flash -m 35 -x 0.015 -M 140 \
			-t {threads} {input.fwd} {input.rev} \
			-d output/{wildcards.species}/{wildcards.smp}/merged \
			-o overlapped \
			&>output/{wildcards.species}/{wildcards.smp}/merged/flash.LOG
		"""

rule minia_assembly:
	input: 
		fwd="output/{species}/{smp}/merged/overlapped.notCombined_1.fastq", 
		rev="output/{species}/{smp}/merged/overlapped.notCombined_2.fastq", 
		ext="output/{species}/{smp}/merged/overlapped.extendedFrags.fastq",
	output:
		asmb="output/{species}/{smp}/assembly/minia_k61.contigs.fa",
	threads:
		8
	shell: """
		module load minia;
		ls -1 {input.ext} {input.fwd} {input.rev} \
			>output/{wildcards.species}/{wildcards.smp}/assembly/input_fastq.fofn;
		minia -max-memory 90000 \
			-kmer-size 61 \
			-out minia_k61 \
			-out-dir output/{wildcards.species}/{wildcards.smp}/assembly/ \
			-nb-cores {threads} \
			-in output/{wildcards.species}/{wildcards.smp}/assembly/input_fastq.fofn \
			&>output/{wildcards.species}/{wildcards.smp}/assembly/minia.LOG
		"""

