#!python

#!/usr/bin/env python3
import os
import sys
from glob import glob
from snakemake.utils import read_job_properties
import pdb

configfile: "config.json"

#workdir: "/global/scratch2/rohitkolora/Rockfish/Genomes/sequencing/illumina"

def get_inputs(wildcards):
    inputs = []    
    pattern = "output/{species}/{smp}/assembly/masurca/RFAM/infernal.cmscan"
    for s in config["SAMPLES"]:
        species, sample = s.split("/")
        inputs.append(pattern.format(species=species,
                                     smp=sample))
    return inputs

rule all: 
    input: 
          get_inputs

rule repeatmasker:
    input: 
        asmb=lambda wildcards:
            "output/{species}/{smp}/assembly/masurca/final.genome.scf.FAS"
            "".format(species=wildcards.species, \
                      smp=wildcards.smp) #, \
    output:
        rpmtbl="output/{species}/{smp}/assembly/masurca/REPEAT/final.genome.scf.FAS.tbl",
        infernaltbl="output/{species}/{smp}/assembly/masurca/RFAM/infernal.cmscan",
    params:
        slurm_opts=lambda wildcards: "-N 1 " \
                                    "--time 72:00:00 " \
                                    "-A co_genomicdata " \
                                    "--qos=savio_lowprio " \
                                    "-p savio " \
                                    "-o logs/noncoding_{smp}.log " \
                                    "-J rna_{smp} " \
                                    .format(smp=wildcards.smp)
    run: 
        shell("""
        module load repeatmasker trnascan infernal;
        RepeatMasker -norna -gff -xsmall \
                -dir output/{species}/{smp}/assembly/masurca/REPEAT/ \
                -pa 24 -div 50 -species vertebrates \
                {input_asmb};
        cmscan --cut_ga --rfam \
                --nohmmonly \
                --tblout output/{species}/{smp}/assembly/masurca/RFAM/infernal.tbl \
                --fmt 2 --cpu 24 \
                --clanin /global/scratch2/rohitkolora/databases/rfam/14.1/Rfam.clanin \
                /global/scratch2/rohitkolora/databases/rfam/14.1/Rfam.cm \
                {input_asmb} >{infernaltbl};
        """.format(input_asmb=input.asmb,\
                smp=wildcards.smp, species=wildcards.species,\
                infernaltbl=output.infernaltbl))
                
