#!python

#!/usr/bin/env python3
import os
import sys
from glob import glob
from snakemake.utils import read_job_properties
import pdb

configfile: "config.json"

#workdir: "/global/scratch2/rohitkolora/Rockfish/Genomes/sequencing/illumina"

def get_inputs(wildcards):
	inputs = []	
	pattern = "output/{species}/{smp}/corrected/corr.0"
	for s in config["SAMPLES"]:
		species, sample = s.split("/")
		inputs.append(pattern.format(species=species,
									 smp=sample))
	return inputs

rule all: 
	input: 
  		get_inputs
    #expand("output/{smp}/assembly/minia_k61.contigs.fa", smp=config["SAMPLES"])

rule error_correction:
	input: 
		fwd=lambda wildcards: glob("fastq/{sp}/{smp}/*_R1_*.fastq".format(sp=wildcards.species,smp=wildcards.smp)), 
		rev=lambda wildcards: glob("fastq/{sp}/{smp}/*_R2_*.fastq".format(sp=wildcards.species,smp=wildcards.smp))
	output: 
		fwd="output/{species}/{smp}/corrected/corr.0",
		rev="output/{species}/{smp}/corrected/corr.1"
	threads:
		16
	shell: 
		"""
		module load musket gcc/6.3.0;
		musket -omulti output/{wildcards.species}/{wildcards.smp}/corrected/corr \
			-p {threads} \
			-inorder \
			-k 21 536870912 \
			{input.fwd} {input.rev} \
			&>output/{wildcards.species}/{wildcards.smp}/corrected/musket.LOG;
	  	"""
    
