#!python

#!/usr/bin/env python3
import os
import json
import sys
from glob import glob
from snakemake.utils import read_job_properties
import pdb

configfile:"pathchange_config2.json"

def get_inputs(wildcards):
    inputs = []
    for sinfo in config["illumina_samples"]:
        pattern = "calls/{species}/{sample}/{identity}/variants.vcf.gz"
        species, sample, identity = sinfo.split("/")
        inputs.append(pattern.format\
            (species=species,sample=sample,identity=identity))
    return inputs


rule all:
    input:
        get_inputs


rule submitting:    
    input:
        infile=lambda wildcards: "calls/{species}/{sample}/{identity}/Snakefile"
    output:
        outfile="calls/{species}/{sample}/{identity}/variants.vcf.gz",
    params:
        slurm_opts=lambda wildcards: "-N 1 " \
                                    "--time 0-48:00:00 " \
                                    "-A co_genomicdata " \
                                    "--qos=savio_lowprio " \
                                    "-p savio3_bigmem " \
                                    "-o logs/creation.log " \
                                    "-J {sample} " \ 
                                    .format(sample=wildcards.sample)

    shell:"""
            cd calls/{wildcards.species}/{wildcards.sample}/{wildcards.identity}/;
            snakemake --rerun-incomplete -j 1151
          """

